services:
  go_app_dev:
    container_name: 'go_app_dev'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      POSTGRES_DB: "converter"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  postgres:
    image: postgres:13
    container_name: 'postgres'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: converter
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste

volumes:
  external-storage:
    external: true
