services:
  go_app_dev:
    container_name: "go_app_dev"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      POSTGRES_DB: "converter"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"

      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERTION_EXCHANGE: "conversion_exchange"
      CONVERTION_QUEUE: "video_conversion_queue"
      CONVERTION_KEY: "conversion"
      CONFIRMATION_KEY: "finish-conversion"
      CONFIRMATION_QUEUE: "video_confirmation_queue"
    depends_on:
      - postgres
      - rabbitmq

    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  postgres:
    image: postgres:13
    container_name: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: converter
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  external-storage:
    external: true
